skel/blog/urls.py
from django.conf.urls.defaults import *
from skel.core.sitemaps import GenericSitemap
from skel.generic.views import GenericView, ArchiveView, YearView, MonthView, DayView, DetailView
from skel.generic import GenericSuite
from skel.blog.models import Entry
from skel.blog import settings, feeds

# Create a suite for all entries.
urlpatterns = GenericSuite(Entry.objects.all()).urls


# Create entry date based URLs.
entry_dict = {
    'queryset': Entry.objects.all(),
    'date_field': 'published',
}


# Create core sitemaps.
core_sitemaps = {
    'blog': GenericSitemap(entry_dict, priority=0.6),
}


# Create syndication feeds.
blog_feeds = {'': feeds.EntryFeed}


# Create tagging URLs.
if settings.SKEL_BLOG_TAGGING_ENABLED:
    tag_dict = {
        'queryset_or_model': entry_dict['queryset'],
        'template_name': 'blog/tag.html',
        'allow_empty': True,
    }
    urlpatterns += patterns('tagging.views',
        url(r'^tag/(?P<tag>[^/]+)/$', 'tagged_object_list', tag_dict,
            name='tag'),
    )
    blog_feeds['tag'] = feeds.EntryTagFeed


# Create entry category URLs.
if settings.SKEL_BLOG_CATEGORIES_ENABLED:    
    category_dict = {
        'queryset': entry_dict['queryset'],
        'template_name': 'blog/category.html',
        'allow_empty': True,
        'paginate_by': 2,
    }
    urlpatterns += patterns('skel.categories.views',
        url(r'^category/(?P<slug>[^/]+)/$', 'category_object_list',
            category_dict, name='category'),
    )
    blog_feeds['category'] = feeds.EntryCategoryFeed


# Create feeds URLs.
if settings.SKEL_BLOG_FEEDS_ENABLED:
    urlpatterns += patterns('django.contrib.syndication.views',
        url(r'^feed/$', 'feed', {'url': '', 'feed_dict': blog_feeds}, name='feed'),
        url(r'^feed/(?P<url>.*)/$', 'feed', {'feed_dict': blog_feeds}),
    )


# Register default global URLs.
core_urlpatterns = patterns('',
    url(r'^blog/', include((urlpatterns, 'blog', 'blog'))),
)

skel/comments/urls.py
from django.conf.urls.defaults import *

# Register default global URLs.
core_urlpatterns = patterns('',
    (r'^comments/', include('django.contrib.comments.urls')),
)

skel/core/urls.py
import sys
from django.conf.urls.defaults import *
from skel.core import settings

urlpatterns = []
sitemaps = {}

# Import any core_urlpatterns and core_sitemaps Skel apps define.
for app_name in settings.INSTALLED_APPS:
    if not app_name.startswith('skel.'):
        continue
    urls_module_name = '.'.join([app_name, 'urls'])
    try:
        mod = __import__(urls_module_name)
    except ImportError:
        continue
    urls_module = sys.modules[urls_module_name]
    if hasattr(urls_module, 'core_urlpatterns'):
        urlpatterns += urls_module.core_urlpatterns
    if hasattr(urls_module, 'core_sitemaps'):
        sitemaps.update(urls_module.core_sitemaps)


if settings.SKEL_CORE_SERVE_MEDIA:
    urlpatterns += patterns('django.views.static',
        url(r'^static/(?P<path>.*)$', 'serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )


if settings.SKEL_CORE_SERVE_ADMIN:
    from django.contrib import admin
    admin.autodiscover()
    urlpatterns += patterns('',
        url('^admin/', include(admin.site.urls)),
    )


if settings.SKEL_CORE_TAGGING_ENABLED:
    tag_dict = {
        'template_name': 'core/tag.html',
        'allow_empty': True,
    }
    urlpatterns += patterns('tagging.views',
        url(r'^tag/(?P<tag>[^/]+)/$', 'tagged_object_list', tag_dict,
            name='tag'),
    )


if settings.SKEL_CORE_SERVE_SITEMAP:
    urlpatterns += patterns('django.contrib.sitemaps.views',
        url(r'^sitemap.xml$', 'sitemap', {'sitemaps': sitemaps}, name='sitemap')
    )


#if settings.SKEL_CORE_DEBUG_TOOLBAR_ENABLED:
    # from debug_toolbar.urls import urlpatterns as debug_toolbar_urls
    # This breaks right now:
    # urlpatterns += debug_toolbar_urls


handler500 = settings.SKEL_CORE_HANDLER_500

skel/markup/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('skel.markup.views',
    url(r'^preview/(?P<engine_name>[a-z]+)/$', 'preview', name='preview'),
)

core_urlpatterns = patterns('',
    url(r'^markup/', include((urlpatterns, 'markup', 'markup'))),
)

skel/portfolio/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from skel.core.managers import PublicSitesObjectManager
from skel.portfolio import settings
from skel.markupeditor.fields import MarkupEditorField
from tagging.fields import TagField
from massmedia.models import Collection


class Client(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    url = models.URLField(blank=True, verify_exists=True)
    sites = models.ManyToManyField(Site)
    public = models.BooleanField(default=True)
    objects = PublicSitesObjectManager()
    admin_manager = models.Manager()
            
    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('portfolio-client-detail', None, {'slug': self.slug})


class Testimonial(models.Model):
    quotee = models.CharField(max_length=255)
    quote = models.TextField()
    url = models.URLField(blank=True, verify_exists=True)
    client = models.ForeignKey(Client, blank=True, null=True)
    sites = models.ManyToManyField(Site)
    public = models.BooleanField(default=True)
    objects = PublicSitesObjectManager()
    admin_manager = models.Manager()

    def __unicode__(self):
        return '%s - %s' % (self.quotee, self.project.title)


class Project(models.Model):
    title = models.CharField(max_length=255)
    public = models.BooleanField(default=True)
    tags = TagField(blank=True)
    media = models.ForeignKey(Collection, blank=True, null=True)
    slug = models.SlugField(unique=True)
    sites = models.ManyToManyField(Site)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=datetime.datetime.now)
    summary = MarkupEditorField(blank=True)
    description = MarkupEditorField()

    testimonials = models.ManyToManyField(Testimonial, blank=True, null=True)
    contributors = models.ManyToManyField(User, blank=True, null=True, related_name='projects_contributes_to')
    maintainers = models.ManyToManyField(User, blank=True, null=True, related_name='projects_maintained')
    started = models.DateTimeField(blank=True, null=True)
    finished = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=255, blank=True)
    client = models.ForeignKey(Client, blank=True, null=True)
    role = models.CharField(max_length=255, blank=True)
    url = models.URLField(blank=True, verify_exists=True)
    
    objects = PublicSitesObjectManager()
    admin_manager = models.Manager()
    
    class Meta:
        ordering = ('-published',)
        get_latest_by = 'published'
        
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ('portfolio-project-detail', None, {'slug': self.slug})
        
    @property
    def comments_enabled(self):
        if settings.PORTFOLIO_AUTO_CLOSE_COMMENTS_DAYS > 0:
            delta = datetime.datetime.now() - self.published
            return delta.days < settings.PORTFOLIO_AUTO_CLOSE_COMMENTS_DAYS
        return settings.PORTFOLIO_COMMENTS_ENABLED and self.public

# if settings.PORTFOLIO_CATEGORIES_ENABLED:
from skel import categories
categories.register(Project)

skel/generic/views/base.py
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponse
from django.template import RequestContext

class GenericView(object):
    """
    Parent class for all generic views.
    """
            
    def __init__(self, **kwargs):
        self._load_config_values(kwargs,
            context_processors = None,
            mimetype = 'text/html',
            template_loader = None,
            template_name = None,
            current_app = None,
        )
        if kwargs:
            raise TypeError("__init__() got an unexpected keyword argument '%s'" % iter(kwargs).next())
    
    def __call__(self, request, object=None):
        template = self.get_template(request, object)
        context = self.get_context(request, object)
        mimetype = self.get_mimetype(request, object)
        response = self.get_response(request, object, template, context, mimetype=mimetype)
        return response
    
    def get_template(self, request, obj):
        """
        Get a ``Template`` object for the given request.
        """
        names = self.get_template_names(request, obj)
        if not names:
            raise ImproperlyConfigured("'%s' must provide template_name." % self.__class__.__name__)
        return self.load_template(request, obj, names)

    def get_template_names(self, request, obj):
        """
        Return a list of template names to be used for the request. Must return
        a list. May not be called if get_template is overridden.
        """ 
        if self.template_name is None:
            return []                       
        elif isinstance(self.template_name, basestring):
            return [self.template_name]
        else:
            return self.template_name
    
    def load_template(self, request, obj, names=[]):
        """
        Load a template, using self.template_loader or the default.
        """
        return self.get_template_loader(request, obj).select_template(names)
    
    def get_template_loader(self, request, obj):
        """
        Get the template loader to be used for this request. Defaults to 
        ``django.template.loader``.
        """
        import django.template.loader
        return self.template_loader or django.template.loader
            
    def get_context(self, request, obj, context=None):
        """
        Get the context. Must return a Context (or subclass) instance.
        """
        processors = self.get_context_processors(request, obj)
        if context is None:
            context = {}
        context['current_app'] = self.current_app
        return RequestContext(request, context, processors)

    def get_context_processors(self, request, obj):
        """
        Get the context processors to be used for the given request.
        """
        return self.context_processors

    def get_mimetype(self, request, obj):
        """
        Get the mimetype to be used for the given request.
        """
        return self.mimetype
        
    def get_response(self, request, obj, template, context, **httpresponse_kwargs):
        """
        Construct an `HttpResponse` object given the template and context.
        """
        return HttpResponse(template.render(context), **httpresponse_kwargs)
        
    def _load_config_values(self, initkwargs, **defaults):
        """
        Set on self some config values possibly taken from __init__, or
        attributes on self.__class__, or some default.
        """
        for k in defaults:
            default = getattr(self.__class__, k, defaults[k])
            value = initkwargs.pop(k, default)
            setattr(self, k, value)

skel/portfolio/templates/portfolio/base.html
{% extends "base.html" %}


{% block title %}Portfolio - {{ block.super }}{% endblock %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/pygments.css" type="text/css" media="screen, projection" />
{% endblock %}


{% block rss %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url feed-root "projects" %}" />
{% endblock %}


{% block content %}
<div id="content" class="grid_9">
    
    {% block portfolio-title %}
        <h1><a href="{% url portfolio-project-list %}" title="Portfolio">Portfolio</a></h1>
    {% endblock %}
    
    {% block portfolio-content %}
    {% endblock %}
    
</div>
{% endblock %}

skel/portfolio/templates/portfolio/project.html
{% load comments tagging_tags %}

{% get_comment_count for project as comment_count %}
{% tags_for_object project as tags %}

<p>

    {% if project.url %}
        Project URL: <a href="{{ project.url }}" title="{{ project.title }}">{{ project.url }}</a>
        <br />
    {% endif %}
    
    {% if tags %}
        Tags:
        {% for tag in tags %}
            <a href="{% url portfolio-project-tag-detail tag.name %}" rel="tag">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
        <br />
    {% endif %}
    
    {% if project.categories.all %}
        Categories:
        {% for category in project.categories.all %}
            <a href="{% url portfolio-project-category-detail category.slug %}" rel="tag">{{ category.name }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
        <br />
    {% endif %}
    
    {% if project.client %}
        {% if project.client.url %}
        Client: <a href="{{ project.client.url }}">{{ project.client.name }}</a>
        {% else %}
        Client: {{ project.client.name }}
        {% endif %}
        <br />
    {% endif %}

    {% if project.role %}
        Role: {{ project.role }}
        <br />
    {% endif %}

</p>

{% if not show_detail %}
    {{ project.summary_rendered }}
    
{% else %}
    {{ project.description_rendered }}
    
    
    {% if project.testimonial_set.all %}
        <h2>Client Testimonials</h2>
        {% for t in project.testimonial_set.all %}
            <p>{{ t.quote }}</p>
            <p>
                -- {% if t.quotee %}{{ t.quotee }}{% if t.client %},{% endif %}{% endif %} 
                   {% if t.client %}<a href="{{ t.client.url }}" title="{{ t.client.name }}">
                                    {{ t.client.name }}</a>{% endif %}
            </p>
        {% endfor %}
    {% endif %}
    
{% endif %}

skel/portfolio/templates/portfolio/project_category_detail.html
{% extends "portfolio/base.html" %}

{% block title %}Projects in {{ category.name }} Category - {{ block.super }}{% endblock %}

{% block portfolio-title %}
    <h1><a href="{% url portfolio-project-category-detail category.slug %}" title="Projects in {{ category.name }} Category">Projects in {{ category.name }} Category</a></h1>
{% endblock %}

{% block portfolio-content %}
    {% for project in object_list %}
        <h2><a href="{{ project.get_absolute_url }}" title="{{ project.title }}">{{ project.title }}</a></h2>
        {% include "portfolio/project.html" %}
    {% empty %}
        <p>No projects in in {{ category.name }} Category.</p>
    {% endfor %}
{% endblock %}

skel/portfolio/templates/portfolio/project_detail.html
{% extends "portfolio/base.html" %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/theme/ui.all.css" type="text/css" media="screen, projection" />
{% endblock %}


{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery/jquery.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery/jquery.ui.all.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/hartzog/hz.core.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/hartzog/hz.splitpane.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/hartzog/hz.markupeditor.js"></script>
    <script type="text/javascript">
    $(function() {
        var markups = $.hz.markupeditor.defaults.markups.slice(0,2);
        $('.hz-markupedit')
            .css({fontFamily: 'monospace'})
            .each(function() {
                    var select = $('select[name=' + $(this).attr('name') + '_markup]');
                    select.parent().hide();
                    $(this).markupeditor({
                        markups: markups,
                        select: function(e, ui) {
                            select.children('[value=' + ui.markup.id + ']')
                                .attr({selected: true});
                        },
                        initial: select.val(),
                    });
                });
    });
    </script>
{% endblock %}


{% block title %}{{ object.title }} - {{ block.super }}{% endblock %}


{% block portfolio-title %}
    <h1><a href="{{ object.get_absolute_url }}" title="{{ object.title }}">{{ object.title }}</a></h1>
{% endblock %}


{% block portfolio-content %}
    {% with object as project %}
    {% with 1 as show_detail %}
        {% include "portfolio/project.html" %}
    {% endwith %}
    {% endwith %}
{% endblock %}

skel/portfolio/templates/portfolio/project_list.html
{% extends "portfolio/base.html" %}

{% block title %}Projects - {{ block.super }}{% endblock %}

{% block portfolio-title %}
    <h1><a href="{% url portfolio-project-list %}">Projects</a></h1>
{% endblock %}

{% block portfolio-content %}
    {% for project in object_list %}
        <h2><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h2>
        {% include "portfolio/project.html" %}
    {% empty %}
        <p>No projects.</p>
    {% endfor %}
{% endblock %}

skel/portfolio/templates/portfolio/project_tag.html
{% extends "portfolio/base.html" %}


{% block title %}Projects Tagged "{{ tag.name }}" - {{ block.super }}{% endblock %}

{% block portfolio-title %}
    <h1><a href="{% url portfolio-project-tag-detail tag %}">Projects Tagged "{{ tag.name }}"</a></h1>
{% endblock %}

{% block portfolio-content %}
    {% for project in object_list %}
        <h2><a href="{{ project.get_absolute_url }}" title="{{ project.title }}">{{ project.title }}</a></h2>
        {% include "portfolio/project.html" %}
    {% empty %}
        <p>No projects tagged "{{ tag.name }}".</p>
    {% endfor %}
{% endblock %}

skel/portfolio/templates/portfolio/project_tag_detail.html
{% extends "portfolio/base.html" %}


{% block title %}Projects Tagged "{{ tag.name }}" - {{ block.super }}{% endblock %}

{% block portfolio-title %}
    <h1><a href="{% url portfolio-project-tag-detail tag %}" title="Projects Tagged {{ tag.name }}">Projects Tagged "{{ tag.name }}"</a></h1>
{% endblock %}

{% block portfolio-content %}
    {% for project in object_list %}
        <h2><a href="{{ project.get_absolute_url }}" title="{{ project.title }}">{{ project.title }}</a></h2>
        {% include "portfolio/project.html" %}
    {% empty %}
        <p>No projects tagged "{{ tag.name }}".</p>
    {% endfor %}
{% endblock %}

skel/portfolio/templates/portfolio/recent_projects.html
{% load generic_content humanize %}

{% get_latest_objects portfolio.project 8 as latest_projects %}

{% if latest_projects %}
    <ul class="portfolio-recent-projects">
    {% for project in latest_projects %}
        <li>
            <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
            <abbr title="{{ project.published|date:"Y-m-dTH:i:sQ" }}">{{ project.published|naturalday:"M j" }}</abbr>
        </li>
    {% endfor %}
    </ul>
    <p><a href="{% url portfolio-project-list %}" class="button-right">Read more</a></p>
{% else %}
    <p>No projects</p>
{% endif %}